import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
        <header className="w-full bg-white shadow-sm mb-6">
          <div className="max-w-6xl mx-auto flex items-center justify-between py-4 px-4">
            <div className="flex items-center gap-3">
              <div className="rounded-full bg-green-100 p-2">
                <svg width="28" height="28" fill="none" viewBox="0 0 24 24"><path d="M12 21C12 21 4 13.5 4 8.5C4 5.46243 6.46243 3 9.5 3C11.1569 3 12 4.5 12 4.5C12 4.5 12.8431 3 14.5 3C17.5376 3 20 5.46243 20 8.5C20 13.5 12 21 12 21Z" stroke="#22C55E" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
              </div>
              <div>
                <div className="font-bold text-lg leading-tight">Environmental Monitor</div>
                <div className="text-xs text-gray-500 leading-tight">Pollution Data Dashboard</div>
              </div>
            </div>
            <button
              onClick={() => {
                localStorage.removeItem("token");
                window.location.href = "/login";
              }}
              className="bg-white border border-gray-300 px-4 py-2 rounded font-semibold hover:bg-gray-100 transition text-gray-700"
            >
              Logout
            </button>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
